config/routes.rb
 Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'static_pages#index'
  resources :games
  namespace :games do
    resources :pieces, only: [:show, :update]
  end
  resources :users, only: :show
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChessGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to "New Game", new_game_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
              </li>
          </ul>
      </div>
      <div class="mx-auto order-0">
          <%= link_to "Night-writers Chess Game", root_path, class: "navbar-brand mx-auto" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
              <span class="navbar-toggler-icon"></span>
          </button>
      </div>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
          <ul class="navbar-nav ml-auto">
            <% if current_user %>
              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
      </div>
    </nav>
    
    
    <% if notice.present? %>
      <p class="notice alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-warning"><%= alert %></p>
    <% end %>
  
    <%= yield %>
  </body>
</html>